name: "Container"
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: fizzimg

jobs:
  build_image:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Build Container"
        run: docker build --target=tester . --tag app_image

      - name: "Login to GitHub Packages Docker Registry"
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Tag Images"
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          # todo: allow dynamic tag
          docker tag app_image $IMAGE_ID:latest

      - name: "Push Images"
        run: |
          # todo: allow dynamic tag
          docker push $IMAGE_ID:latest